export const initialUiText = {
  sectionTitles: {
    dashboard: 'Dashboard',
    patientInfo: 'Patient Information',
    medicalHistory: 'Medical History',
    lifestyle: 'Lifestyle Assessment',
    senses: 'Sense Organ Assessment',
    healthReport: 'Health Report',
    aiInsights: 'AI Health Insights',
  },
  components: {
    header: {
      toggleNav: 'Toggle navigation menu',
      selectLanguage: 'Select Language',
      toggleUserMenu: 'Toggle user menu',
      myAccount: 'My Account',
      settings: 'Settings',
      support: 'Support',
      logout: 'Logout',
    },
    chatbot: {
        title: 'AI Health Assistant',
        initialMessage: "Hello! I'm your AI health assistant. How can I help you today?",
        errorMessage: "Sorry, I'm having trouble connecting. Please try again later.",
        inputPlaceholder: 'Type a message...',
    },
    dashboard: {
      title: 'Data Summary',
      description: 'A comprehensive health data visualization and export system.',
      exportButton: 'Export PDF',
      patientOverview: {
        title: 'Patient Overview',
        bmi: 'BMI:',
      },
      medicalHistory: {
        title: 'Medical History',
        keyConditions: 'Key Conditions:',
        medications: 'Medications:',
      },
      lifestyle: {
        title: 'Lifestyle Score',
      },
      senseOrgans: {
        title: 'Sense Organs',
        dental: 'Dental:',
        dentalDesc: '2 teeth with sensitivity issues.',
        eyes: 'Eyes:',
        eyesDesc: 'Reports Myopia (nearsightedness).',
      },
      symptomTrend: {
        title: 'Symptom Severity Trend',
        description: 'Severity rated on a 1-10 scale over 6 months.',
      },
    },
    patientInfo: {
      title: 'Patient Basic Information',
      description: 'Collect comprehensive demographic and physical information about the patient.',
      uploadButton: 'Upload Photo',
      fullName: 'Full Name',
      fullNamePlaceholder: 'John Doe',
      age: 'Age',
      gender: 'Gender',
      genderMale: 'Male',
      genderFemale: 'Female',
      genderNonBinary: 'Non-binary',
      email: 'Email',
      emailPlaceholder: 'john.doe@example.com',
      phone: 'Phone Number',
      address: {
        label: 'Address',
        line1: 'Address Line 1',
        line2: 'Address Line 2 (Optional)',
        city: 'City',
        district: 'District / County',
        state: 'State / Province',
        postalCode: 'Postal / Zip Code',
      },
      height: 'Height (cm)',
      weight: 'Weight (kg)',
      uniqueId: 'Unique ID',
      dob: 'Date of Birth',
      birthTime: 'Birth Time',
      birthPlace: 'Birth Place',
      birthPlacePlaceholder: 'City, State, Country',
      deliveryType: {
        label: 'Delivery Type',
        placeholder: 'Select type',
        normal: 'Normal',
        cSection: 'C-Section',
        forceps: 'Forceps',
        vacuum: 'Vacuum',
      },
      deliveryTime: {
        label: 'Delivery Time',
        placeholder: 'e.g., Full-term, Preterm',
      },
    },
    medicalHistory: {
        title: 'Medical History',
        description: 'Comprehensive medical background collection with detailed tracking.',
        tabs: {
            'family-history': 'Family History',
            'past-history': 'Past History',
            'current-situation': 'Current Situation',
            medications: 'Medications',
            documents: 'Documents',
        },
        familyHistory: {
            title: 'Family History',
            description: "Select any conditions that run in the patient's family.",
            searchPlaceholder: 'Search conditions...',
            otherPlaceholder: 'Other (please specify)',
        },
        pastHistory: {
            title: 'Past Medical History',
            description: 'A list of past conditions, surgeries, and treatments.',
            addButton: 'Add Condition',
            conditionPlaceholder: 'Condition Name',
            resolved: 'Resolved',
        },
        currentSituation: {
            title: 'Current Medical Situation',
            description: 'Track ongoing health issues and complications.',
            symptomsLabel: 'Symptoms',
            symptomsPlaceholder: 'Describe current symptoms...',
            severityLabel: 'Severity (1-10)',
            impactLabel: 'Impact on Daily Life',
            impactPlaceholder: 'How do these symptoms affect daily activities?',
        },
        medications: {
            title: 'Current Medications',
            description: 'Comprehensive medication management and tracking.',
            addButton: 'Add Medication',
            namePlaceholder: 'Medication Name',
            dosagePlaceholder: 'Dosage (e.g., 10mg, once daily)',
            descriptionPlaceholder: 'Description / Reason',
        },
        documents: {
            title: 'Document Management',
            description: 'Centralized medical document storage and organization.',
            reports: 'Medical Reports',
            reportsDesc: 'PDF up to 10MB',
            prescriptions: 'Prescriptions',
            prescriptionsDesc: 'PDF/Image',
            photos: 'Problem Photos',
            photosDesc: 'JPEG/PNG',
            uploadButton: 'Upload',
        },
    },
    lifestyle: {
        title: 'Lifestyle Assessment',
        description: 'Comprehensive lifestyle evaluation across key areas.',
        tabs: {
            sleep: 'Sleep',
            diet: 'Diet',
            activity: 'Activity',
            stress: 'Stress',
            substance: 'Substance',
            stool: 'Stool',
            urine: 'Urine',
            menstruation: 'Menstruation',
        },
        photoAndNotes: {
            title: 'Additional Information for {section}',
            notesLabel: 'Notes',
            notesPlaceholder: 'Any additional notes for {section}...',
            photoLabel: 'Upload Related Photo',
        },
        sleep: {
            title: 'Sleep Patterns',
            bedtime: 'Bedtime',
            wakeTime: 'Wake-up Time',
            quality: 'Sleep Quality',
            selectQuality: 'Select quality',
            qualityOptions: ['Excellent', 'Good', 'Fair', 'Poor'],
            qualityValues: { excellent: 'Excellent', good: 'Good', fair: 'Fair', poor: 'Poor' },
            issues: 'Sleep Issues (select all that apply)',
            issueOptions: ['Insomnia', 'Sleep apnea', 'Snoring', 'Restless legs', 'Nightmares', 'Frequent awakening'],
            dreams: 'Dreams',
            selectDream: 'Select dream frequency',
            dreamOptions: ['Never / Rarely', 'Sometimes', 'Often', 'Vivid / Memorable'],
            dreamValues: { never: 'Never', sometimes: 'Sometimes', often: 'Often', vivid: 'Vivid' },
        },
        diet: {
            title: 'Dietary Habits',
            dietType: 'Diet Type',
            selectDiet: 'Select diet type',
            dietOptions: ['Omnivore', 'Vegetarian', 'Vegan', 'Pescatarian'],
            dietValues: { omnivore: 'Omnivore', vegetarian: 'Vegetarian', vegan: 'Vegan', pescatarian: 'Pescatarian' },
            waterIntake: 'Daily Water Intake (Liters)',
            hungerLevel: 'Hunger Level (1-10)',
            favoriteFood: 'Favorite Food',
            favoriteFoodPlaceholder: 'e.g., Pizza, Salad, Sushi',
            allergies: 'Food Allergies/Intolerances',
            allergiesPlaceholder: 'e.g., Lactose, Gluten, Nuts',
            taste: {
                title: 'Predominant Tastes (select all that apply)',
                options: { sweet: 'Sweet', sour: 'Sour', salty: 'Salty', bitter: 'Bitter', pungent: 'Pungent', astringent: 'Astringent' },
            },
            thirst: {
                title: 'Thirst Level',
                select: 'Select thirst level',
                options: { low: 'Low', normal: 'Normal', high: 'High' },
            },
        },
        activity: {
            title: 'Physical Activity',
            level: 'Activity Level',
            selectLevel: 'Select activity level',
            levelOptions: ['Sedentary (<30 mins/week)', 'Lightly Active (30-90 mins/week)', 'Moderately Active (90-270 mins/week)', 'Very Active (>270 mins/week)'],
            levelValues: { sedentary: 'Sedentary', lightly: 'Lightly Active', moderately: 'Moderately Active', very: 'Very Active' },
        },
        stress: {
            title: 'Stress & Emotion',
            level: 'Stress Level',
            selectLevel: 'Select stress level',
            levelOptions: ['😌 Low', '😐 Moderate', '😰 High', '😱 Very High'],
            levelValues: { low: 'Low', moderate: 'Moderate', high: 'High', 'very-high': 'Very High' },
            caffeine: 'Caffeine Intake',
            selectCaffeine: 'Select caffeine intake',
            caffeineOptions: ['None (0mg)', 'Low (1-100mg)', 'Moderate (100-300mg)', 'High (300-500mg)', 'Excessive (>500mg)'],
            caffeineValues: { none: 'None', low: 'Low', moderate: 'Moderate', high: 'High', excessive: 'Excessive' },
            emotion: {
                title: 'Primary Emotion Lately',
                select: 'Select primary emotion',
                options: { happy: 'Happy', sad: 'Sad', anxious: 'Anxious', angry: 'Angry', calm: 'Calm', other: 'Other' },
                otherPlaceholder: 'Please specify other emotion',
            }
        },
        substance: {
            title: 'Smoking & Alcohol',
            smoking: 'Smoking Status',
            selectSmoking: 'Select smoking status',
            smokingOptions: ['Never smoked', 'Former smoker', 'Occasional smoker', 'Regular smoker'],
            smokingValues: { never: 'Never smoked', former: 'Former smoker', occasional: 'Occasional smoker', regular: 'Regular smoker' },
            alcohol: 'Alcohol Consumption',
            selectAlcohol: 'Select alcohol consumption',
            alcoholOptions: ['Never', 'Rarely', 'Occasionally', 'Weekly', 'Daily'],
            alcoholValues: { never: 'Never', rarely: 'Rarely', occasionally: 'Occasionally', weekly: 'Weekly', daily: 'Daily' },
        },
        stool: {
            title: 'Stool Analysis',
            color: 'Stool Color',
            type: 'Stool Type (Bristol Stool Chart)',
            selectType: 'Select stool type',
            typeOptions: ['Type 1: Separate hard lumps (hard to pass)', 'Type 2: Sausage-shaped, but lumpy', 'Type 3: Like a sausage but with cracks on surface', 'Type 4: Like a sausage or snake, smooth and soft', 'Type 5: Soft blobs with clear-cut edges', 'Type 6: Fluffy pieces with ragged edges, mushy', 'Type 7: Watery, no solid pieces, liquid'],
            problems: 'Stool Problems (select all that apply)',
            problemOptions: ['Constipation', 'Diarrhea', 'Painful Movements', 'Blood in Stool', 'Mucus in Stool', 'Undigested Food'],
        },
        urine: {
            title: 'Urine Analysis',
            color: 'Urine Color',
            day_frequency: 'Daytime Frequency',
            select_day_frequency: 'Select daytime frequency',
            dayFrequencyOptions: { normal: 'Normal (4-7 times)', frequent: 'Frequent (>7 times)', infrequent: 'Infrequent (<4 times)'},
            night_frequency: 'Nighttime Frequency',
            select_night_frequency: 'Select nighttime frequency',
            nightFrequencyOptions: { '0-1': '0-1 time', '2-3': '2-3 times', '4+': '4+ times' },
            problems: 'Urine Problems (select all that apply)',
            problemOptions: ['Pain or Burning', 'Difficulty Starting', 'Weak Stream', 'Urgency', 'Incontinence / Leakage', 'Cloudy Urine', 'Strong Odor'],
        },
        menstruation: {
            title: 'Menstrual Cycle Details',
            lastPeriod: 'Last Period Start Date',
            cycleLength: 'Cycle Length (days)',
            duration: 'Duration (days)',
            regularity: {
                title: 'Is your cycle regular?',
                select: 'Select option',
                yes: 'Yes',
                no: 'No',
            },
            flow: {
                title: 'Flow',
                select: 'Select flow type',
                options: { light: 'Light', medium: 'Medium', heavy: 'Heavy' },
            },
            bloodColor: {
                title: 'Blood Color',
            },
            symptoms: {
                title: 'Symptoms (select all that apply)',
                options: ['Cramps', 'Bloating', 'Headaches', 'Mood Swings', 'Fatigue', 'Acne', 'Breast Tenderness'],
            },
            painLevel: 'Pain Level (1-10)',
        }
    },
    senses: {
        title: 'Sense Organ & System Assessment',
        description: 'Comprehensive sensory system evaluation with interactive tools.',
        tabs: {
            dental: 'Dental',
            'other-systems': 'Other Sense Organs',
        },
        photoAndNotes: {
            title: 'Additional Details for {section}',
            problemDetails: 'Problem Details',
            problemPlaceholder: 'Describe the problem in detail...',
            photoLabel: 'Upload Related Photo',
        },
        dental: {
            title: 'Interactive Dental Diagram',
            description: 'Select teeth and specify conditions.',
            conditionsLabel: 'Dental Conditions',
        },
        otherSystems: {
            title: 'Organ & System Review',
            description: 'Note any issues with the following systems.',
        },
    },
    healthReport: {
        title: 'Comprehensive Health Report',
        generatedOn: 'Generated on:',
        patientInfo: {
            title: 'Patient Information',
            name: 'Full Name',
            uniqueId: 'Unique ID',
            age: 'Age',
            gender: 'Gender',
            email: 'Email',
            phone: 'Phone',
            height: 'Height',
            weight: 'Weight',
            address: 'Address',
        },
        medicalHistory: {
            title: 'Medical History',
            pastConditions: 'Past Conditions',
            diagnosed: 'Diagnosed',
            resolved: 'Resolved',
            ongoing: 'Ongoing',
            noPastConditions: 'No past conditions reported.',
            currentMedications: 'Current Medications',
            noCurrentMedications: 'No current medications reported.',
            uploadedDocuments: 'Uploaded Documents',
            report: 'Report',
            prescription: 'Prescription',
            photo: 'Photo',
            noDocuments: 'No documents uploaded.',
        },
        placeholder: 'Lifestyle Assessment, Sense Organs, and other data will be displayed here.',
    },
    aiInsights: {
        title: 'AI Health Analysis Engine',
        description: 'Click the button below to generate AI-powered health insights based on the complete patient report. Ensure all sections have been filled out for the most accurate analysis.',
        buttonText: 'Generate Insights from Full Report',
        buttonLoading: 'Analyzing Full Report...',
        errorTitle: 'Error Generating Insights',
        errorCardTitle: 'Error',
        resultsTitle: 'AI-Generated Insights',
        disclaimer: 'Disclaimer: The analysis below is generated by an AI and is for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.',
        summary: 'Diagnostic Summary',
        conditions: 'Potential Conditions & Problem Areas',
        recommendations: 'Lifestyle & Wellness Recommendations',
        nextSteps: 'Suggested Next Steps & Consultations',
    }
  }
};
