export const initialUiText = {
  sectionTitles: {
    dashboard: 'Dashboard',
    patientInfo: 'Patient Information',
    medicalHistory: 'Medical History',
    lifestyle: 'Lifestyle Assessment',
    senses: 'Sense Organ Assessment',
    payment: 'Payment',
    healthReport: 'Health Report',
    aiInsights: 'AI Health Insights',
    patientImprovementReview: 'Patient Improvement Review',
    consultation: 'Consultation',
  },
  components: {
    header: {
      toggleNav: 'Toggle navigation menu',
      selectLanguage: 'Select Language',
      toggleUserMenu: 'Toggle user menu',
      myAccount: 'My Account',
      settings: 'Settings',
      support: 'Support',
      logout: 'Logout',
      saveButton: 'Save Progress',
      saveProgress: {
          title: 'Progress Saved!',
          description: 'Your changes have been saved in the application state.'
      }
    },
    chatbot: {
        title: 'AI Health Assistant',
        initialMessage: "Hello! I'm your AI health assistant. How can I help you today?",
        errorMessage: "Sorry, I'm having trouble connecting. Please try again later.",
        inputPlaceholder: 'Type a message...',
    },
    dashboard: {
      title: 'Data Summary',
      description: 'A comprehensive health data visualization and export system.',
      exportButton: 'Export PDF',
      patientOverview: {
        title: 'Patient Overview',
        bmi: 'BMI:',
      },
      medicalHistory: {
        title: 'Medical History',
        keyConditions: 'Key Conditions:',
        medications: 'Medications:',
      },
      lifestyle: {
        title: 'Lifestyle Score',
      },
      senseOrgans: {
        title: 'Sense Organs',
        dental: 'Dental:',
        dentalDesc: '2 teeth with sensitivity issues.',
        eyes: 'Eyes:',
        eyesDesc: 'Reports Myopia (nearsightedness).',
      },
      symptomTrend: {
        title: 'Symptom Severity Trend',
        description: 'Severity rated on a 1-10 scale over 6 months.',
      },
    },
    patientInfo: {
      title: 'Patient Basic Information',
      description: 'Collect comprehensive demographic and physical information about the patient.',
      uploadButton: 'Upload Photo',
      fullName: 'Full Name',
      fullNamePlaceholder: 'John Doe',
      age: 'Age',
      gender: 'Gender',
      genderMale: 'Male',
      genderFemale: 'Female',
      genderNonBinary: 'Non-binary',
      email: 'Email',
      emailPlaceholder: 'john.doe@example.com',
      phone: 'Contact Number',
      address: {
        label: 'Address',
        line1: 'Address Line 1',
        line2: 'Address Line 2 (Optional)',
        city: 'City',
        district: 'District / County',
        state: 'State / Province',
        postalCode: 'Postal / Zip Code',
      },
      height: 'Height (cm)',
      weight: 'Weight (kg)',
      uniqueId: 'Unique ID',
      generateButton: 'Generate',
      idGenerationError: {
        title: 'Missing Information',
        description: 'Please enter a name and phone number before generating an ID.'
      },
      dob: 'Date of Birth',
      birthTime: 'Birth Time',
      birthPlace: 'Birth Place',
      birthPlacePlaceholder: 'City, State, Country',
      deliveryType: {
        label: 'Delivery Type',
        placeholder: 'Select type',
        normal: 'Normal',
        cSection: 'C-Section',
        forceps: 'Forceps',
        vacuum: 'Vacuum',
      },
      deliveryTime: {
        label: 'Delivery Time',
        placeholder: 'e.g., Full-term, Preterm',
      },
      occupation: 'Occupation',
      occupationPlaceholder: 'e.g., Software Engineer, Teacher',
      maritalStatus: {
        label: 'Marital Status',
        placeholder: 'Select status',
        single: 'Single',
        married: 'Married',
        divorced: 'Divorced',
        widowed: 'Widowed',
      },
      dateOfVisit: 'Date of Visit',
      referredBy: 'Referred By',
      referredByPlaceholder: 'e.g., Dr. Smith',
    },
    medicalHistory: {
        title: 'Medical History',
        description: 'Comprehensive medical background collection with detailed tracking.',
        tabs: {
            'chief-complaints': 'Chief Complaints',
            'present-illness': 'Present Illness',
            'past-history': 'Past History',
            'medications': 'Medications',
            'family-history': 'Family History',
            'documents': 'Documents',
        },
        chiefComplaints: {
            title: 'Chief Complaints',
            description: 'The main problem or symptom that brought the patient here.',
            addButton: 'Add Complaint',
            complaintPlaceholder: 'Main problem or symptom',
            durationPlaceholder: 'Duration of symptom(s)',
            orderPlaceholder: 'Order of appearance',
            noComplaints: 'No chief complaints reported.',
            duration: 'Duration',
            order: 'Order',
        },
        presentIllness: {
            title: 'History of Present Illness',
            description: 'A detailed account of the current symptoms.',
            symptomsLabel: 'Describe the symptom(s) in detail',
            symptomsPlaceholder: 'e.g., Sharp pain in the lower back...',
            onset: {
                label: 'Onset',
                placeholder: 'Select onset',
                sudden: 'Sudden',
                gradual: 'Gradual',
            },
            duration: {
                label: 'Duration',
                placeholder: 'Select duration',
                continuous: 'Continuous',
                intermittent: 'Intermittent',
            },
            progression: {
                label: 'Progression',
                placeholder: 'Select progression',
                improving: 'Improving',
                worsening: 'Worsening',
                static: 'Static',
            },
            frequencyTiming: 'Frequency and Timing',
            frequencyTimingPlaceholder: 'e.g., Twice a day, after meals',
            location: 'Location (if pain)',
            locationPlaceholder: 'e.g., Left knee, abdomen',
            radiation: 'Radiation (does it spread?)',
            radiationPlaceholder: 'e.g., Down the left arm',
            character: 'Character',
            characterPlaceholder: 'e.g., Sharp, dull, throbbing, burning',
            severityLabel: 'Severity (1–10)',
            associatedSymptoms: 'Associated Symptoms',
            associatedSymptomsPlaceholder: 'e.g., Fever, nausea, fatigue',
            aggravatingFactors: 'Aggravating Factors',
            aggravatingFactorsPlaceholder: 'e.g., Movement, food, stress',
            relievingFactors: 'Relieving Factors',
            relievingFactorsPlaceholder: 'e.g., Rest, medication, position',
            previousEpisodes: 'Previous Episodes of Similar Symptoms',
            previousEpisodesPlaceholder: 'Describe any previous episodes',
        },
        pastHistory: {
            title: 'Past Medical History',
            description: 'A list of past conditions, surgeries, and other historical medical events.',
            hospitalizations: {
                title: 'Hospitalizations or Surgeries',
                addButton: 'Add Condition',
                conditionPlaceholder: 'Condition, Surgery Name',
                resolved: 'Resolved',
            },
            trauma: 'History of trauma or accidents',
            traumaPlaceholder: 'Describe any significant trauma or accidents',
            bloodTransfusions: 'History of blood transfusions',
            bloodTransfusionsPlaceholder: 'Details of any blood transfusions',
            allergies: 'Any known allergies (drug, food, environmental)',
            allergiesPlaceholder: 'e.g., Penicillin, Peanuts, Pollen',
            immunizations: 'Immunization status',
            immunizationsPlaceholder: 'e.g., Up-to-date, missing specific vaccines',
        },
        medications: {
            title: 'Medication History',
            description: 'Comprehensive medication management and tracking.',
            prescribed: {
                title: 'Prescribed Medications',
                addButton: 'Add Medication',
                namePlaceholder: 'Medication Name',
                dosagePlaceholder: 'Dosage (e.g., 10mg, once daily)',
                descriptionPlaceholder: 'Reason for prescription',
            },
            supplements: 'Over-the-counter or herbal supplements',
            supplementsPlaceholder: 'e.g., Vitamin D, St. John\'s Wort',
            compliance: {
                label: 'Compliance with prescribed treatment',
                placeholder: 'Select compliance',
                good: 'Good',
                fair: 'Fair',
                poor: 'Poor',
            },
            recentChanges: 'Any recent changes in medication?',
            recentChangesPlaceholder: 'Describe any recent changes',
        },
        familyHistory: {
            title: 'Family History',
            description: "Select any conditions that run in the patient's family and provide details.",
            conditions: {
              title: 'Family Medical Conditions'
            },
            healthStatus: 'Health status of parents, siblings, children',
            healthStatusPlaceholder: 'e.g., Mother (65, alive, hypertension), Father (deceased, 58, heart attack)',
            consanguinity: {
                label: 'History of consanguinity in parents?',
                placeholder: 'Select option',
                yes: 'Yes',
                no: 'No',
                unknown: 'Unknown',
            },
        },
        documents: {
            title: 'Document Management',
            description: 'Centralized medical document storage and organization.',
            reports: 'Medical Reports',
            reportsDesc: 'PDF up to 10MB',
            prescriptions: 'Prescriptions',
            prescriptionsDesc: 'PDF/Image',
            photos: 'Problem Photos',
            photosDesc: 'JPEG/PNG',
            uploadButton: 'Upload',
            noDocuments: 'No documents uploaded.',
        },
    },
    lifestyle: {
        title: 'Lifestyle Assessment',
        description: 'Comprehensive lifestyle evaluation across key areas.',
        tabs: {
            sleep: 'Sleep',
            diet: 'Diet',
            activity: 'Activity',
            stress: 'Stress',
            substance: 'Substance',
            stool: 'Stool',
            urine: 'Urine',
            menstruation: 'Menstruation',
        },
        photoAndNotes: {
            title: 'Additional Information for {section}',
            notesLabel: 'Notes',
            notesPlaceholder: 'Any additional notes for {section}...',
            photoLabel: 'Upload Related Photo',
        },
        sleep: {
            title: 'Sleep Patterns',
            bedtime: 'Bedtime',
            wakeTime: 'Wake-up Time',
            quality: 'Sleep Quality',
            selectQuality: 'Select quality',
            qualityOptions: ['Excellent', 'Good', 'Fair', 'Poor'],
            qualityValues: { excellent: 'Excellent', good: 'Good', fair: 'Fair', poor: 'Poor' },
            issues: 'Sleep Issues (select all that apply)',
            issueOptions: ['Insomnia', 'Sleep apnea', 'Snoring', 'Restless legs', 'Nightmares', 'Frequent awakening'],
            dreams: 'Dreams',
            selectDream: 'Select dream frequency',
            dreamOptions: ['Never / Rarely', 'Sometimes', 'Often', 'Vivid / Memorable'],
            dreamValues: { never: 'Never', sometimes: 'Sometimes', often: 'Often', vivid: 'Vivid' },
        },
        diet: {
            title: 'Dietary Habits',
            dietType: 'Diet Type',
            selectDiet: 'Select diet type',
            dietOptions: ['Omnivore', 'Vegetarian', 'Vegan', 'Pescatarian'],
            dietValues: { omnivore: 'Omnivore', vegetarian: 'Vegetarian', vegan: 'Vegan', pescatarian: 'Pescatarian' },
            waterIntake: 'Daily Water Intake (Liters)',
            hungerLevel: 'Hunger Level (1-10)',
            favoriteFood: 'Favorite Food',
            favoriteFoodPlaceholder: 'e.g., Pizza, Salad, Sushi',
            allergies: 'Food Allergies/Intolerances',
            allergiesPlaceholder: 'e.g., Lactose, Gluten, Nuts',
            taste: {
                title: 'Predominant Tastes (select all that apply)',
                options: { sweet: 'Sweet', sour: 'Sour', salty: 'Salty', bitter: 'Bitter', pungent: 'Pungent', astringent: 'Astringent' },
            },
            thirst: {
                title: 'Thirst Level',
                select: 'Select thirst level',
                options: { low: 'Low', normal: 'Normal', high: 'High' },
            },
        },
        activity: {
            title: 'Physical Activity',
            level: 'Activity Level',
            selectLevel: 'Select activity level',
            levelOptions: ['Sedentary (<30 mins/week)', 'Lightly Active (30-90 mins/week)', 'Moderately Active (90-270 mins/week)', 'Very Active (>270 mins/week)'],
            levelValues: { sedentary: 'Sedentary', lightly: 'Lightly Active', moderately: 'Moderately Active', very: 'Very Active' },
        },
        stress: {
            title: 'Stress & Emotion',
            level: 'Stress Level',
            selectLevel: 'Select stress level',
            levelOptions: ['😌 Low', '😐 Moderate', '😰 High', '😱 Very High'],
            levelValues: { low: 'Low', moderate: 'Moderate', high: 'High', 'very-high': 'Very High' },
            caffeine: 'Caffeine Intake',
            selectCaffeine: 'Select caffeine intake',
            caffeineOptions: ['None (0mg)', 'Low (1-100mg)', 'Moderate (100-300mg)', 'High (300-500mg)', 'Excessive (>500mg)'],
            caffeineValues: { none: 'None', low: 'Low', moderate: 'Moderate', high: 'High', excessive: 'Excessive' },
            emotion: {
                title: 'Primary Emotion Lately',
                select: 'Select primary emotion',
                options: { happy: 'Happy', sad: 'Sad', anxious: 'Anxious', angry: 'Angry', calm: 'Calm', other: 'Other' },
                otherPlaceholder: 'Please specify other emotion',
            }
        },
        substance: {
            title: 'Smoking & Alcohol',
            smoking: 'Smoking Status',
            selectSmoking: 'Select smoking status',
            smokingOptions: ['Never smoked', 'Former smoker', 'Occasional smoker', 'Regular smoker'],
            smokingValues: { never: 'Never smoked', former: 'Former smoker', occasional: 'Occasional smoker', regular: 'Regular smoker' },
            alcohol: 'Alcohol Consumption',
            selectAlcohol: 'Select alcohol consumption',
            alcoholOptions: ['Never', 'Rarely', 'Occasionally', 'Weekly', 'Daily'],
            alcoholValues: { never: 'Never', rarely: 'Rarely', occasionally: 'Occasionally', weekly: 'Weekly', daily: 'Daily' },
        },
        stool: {
            title: 'Stool Analysis',
            color: 'Stool Color',
            type: 'Stool Type (Bristol Stool Chart)',
            selectType: 'Select stool type',
            typeOptions: ['Type 1: Separate hard lumps (hard to pass)', 'Type 2: Sausage-shaped, but lumpy', 'Type 3: Like a sausage but with cracks on surface', 'Type 4: Like a sausage or snake, smooth and soft', 'Type 5: Soft blobs with clear-cut edges', 'Type 6: Fluffy pieces with ragged edges, mushy', 'Type 7: Watery, no solid pieces, liquid'],
            problems: 'Stool Problems (select all that apply)',
            problemOptions: ['Constipation', 'Diarrhea', 'Painful Movements', 'Blood in Stool', 'Mucus in Stool', 'Undigested Food'],
        },
        urine: {
            title: 'Urine Analysis',
            color: 'Urine Color',
            day_frequency: 'Daytime Frequency',
            select_day_frequency: 'Select daytime frequency',
            dayFrequencyOptions: { normal: 'Normal (4-7 times)', frequent: 'Frequent (>7 times)', infrequent: 'Infrequent (<4 times)'},
            night_frequency: 'Nighttime Frequency',
            select_night_frequency: 'Select nighttime frequency',
            nightFrequencyOptions: { '0-1': '0-1 time', '2-3': '2-3 times', '4+': '4+ times' },
            problems: 'Urine Problems (select all that apply)',
            problemOptions: ['Pain or Burning', 'Difficulty Starting', 'Weak Stream', 'Urgency', 'Incontinence / Leakage', 'Cloudy Urine', 'Strong Odor'],
        },
        menstruation: {
            title: 'Menstrual Cycle Details',
            lastPeriod: 'Last Period Start Date',
            cycleLength: 'Cycle Length (days)',
            duration: 'Duration (days)',
            regularity: {
                title: 'Is your cycle regular?',
                select: 'Select option',
                yes: 'Yes',
                no: 'No',
            },
            flow: {
                title: 'Flow',
                select: 'Select flow type',
                options: { light: 'Light', medium: 'Medium', heavy: 'Heavy' },
            },
            bloodColor: {
                title: 'Blood Color',
            },
            symptoms: {
                title: 'Symptoms (select all that apply)',
                options: ['Cramps', 'Bloating', 'Headaches', 'Mood Swings', 'Fatigue', 'Acne', 'Breast Tenderness'],
            },
            painLevel: 'Pain Level (1-10)',
        }
    },
    senses: {
        title: 'Sense Organ & System Assessment',
        description: 'Comprehensive sensory system evaluation with interactive tools.',
        tabs: {
            dental: 'Dental',
            'other-systems': 'Other Sense Organs',
        },
        photoAndNotes: {
            title: 'Additional Details for {section}',
            problemDetails: 'Problem Details',
            problemPlaceholder: 'Describe the problem in detail...',
            photoLabel: 'Upload Related Photo',
        },
        dental: {
            title: 'Interactive Dental Diagram',
            description: 'Select teeth and specify conditions.',
            conditionsLabel: 'Dental Conditions',
        },
        otherSystems: {
            title: 'Organ & System Review',
            description: 'Note any issues with the following systems.',
        },
    },
    payment: {
      title: 'Platform Usage Fee',
      description: 'To continue and generate your AI health report, please complete the one-time platform fee payment.',
      paymentForm: {
          title: 'Complete Payment',
          description: 'You are paying an amount of ₹{amount}.',
          card: {
              tabTitle: 'Credit/Debit Card',
              nameLabel: 'Name on Card',
              namePlaceholder: 'John Doe',
              numberLabel: 'Card Number',
              numberPlaceholder: '•••• •••• •••• ••••',
              expiryMonthLabel: 'Month',
              expiryYearLabel: 'Year',
              cvcLabel: 'CVC',
          },
          upi: {
              tabTitle: 'UPI',
              idLabel: 'UPI ID',
              idPlaceholder: 'yourname@upi',
              or: 'OR',
              gpay: 'GPay',
              phonepe: 'PhonePe',
              paytm: 'Paytm',
          },
          payButton: 'Pay ₹{amount} Securely',
      },
      success: {
          title: 'Payment Successful',
          alertTitle: 'Thank you!',
          alertDescription: 'Your payment has been received. You may now proceed to the next sections.'
      }
    },
    healthReport: {
        title: 'Health Report',
        description: 'A comprehensive summary of the patient\'s health data.',
        downloadButton: 'Download PDF',
        summary: {
            title: 'Your Health Summary',
            thankYou: 'Thank you for trusting us with your health report.',
            stayHealthy: 'Stay on top of your health parameters and take the right steps to stay healthy.',
        },
        atAGlance: {
            title: 'At a glance',
            description: 'Biological-Graphical representation of a blood vessel within a human body, for representation purpose only.',
        },
        detailedReport: {
            title: 'Comprehensive Data Report',
            patientInformation: 'Patient Information',
            name: 'Name',
            age: 'Age',
            gender: 'Gender',
            email: 'Email',
            phone: 'Phone',
            address: 'Address',
            height: 'Height',
            weight: 'Weight',
            uniqueId: 'Unique ID',
            dob: 'Date of Birth',
            birthTime: 'Birth Time',
            birthPlace: 'Birth Place',
            deliveryType: 'Delivery Type',
            deliveryTime: 'Delivery Time',
            occupation: 'Occupation',
            maritalStatus: 'Marital Status',
            dateOfVisit: 'Date of Visit',
            referredBy: 'Referred By',
    
            medicalHistory: 'Medical History',
            chiefComplaints: 'Chief Complaints',
            complaint: 'Complaint',
            duration: 'Duration',
            order: 'Order',
            presentIllness: 'History of Present Illness',
            symptoms: 'Symptoms',
            onset: 'Onset',
            progression: 'Progression',
            frequencyTiming: 'Frequency & Timing',
            location: 'Location',
            radiation: 'Radiation',
            character: 'Character',
            severity: 'Severity',
            associatedSymptoms: 'Associated Symptoms',
            aggravatingFactors: 'Aggravating Factors',
            relievingFactors: 'Relieving Factors',
            previousEpisodes: 'Previous Episodes',
            impact: 'Impact',
            pastHistory: 'Past History',
            pastConditions: 'Conditions/Surgeries',
            trauma: 'Trauma History',
            bloodTransfusions: 'Blood Transfusions',
            allergies: 'Allergies',
            immunizations: 'Immunizations',
            medications: 'Medications',
            prescribed: 'Prescribed',
            supplements: 'Supplements',
            compliance: 'Compliance',
            recentChanges: 'Recent Changes',
            familyHistory: 'Family History',
            familyConditions: 'Conditions',
            familyHealthStatus: 'Family Health Status',
            consanguinity: 'Consanguinity',
            
            lifestyle: 'Lifestyle Assessment',
            sleep: 'Sleep',
            diet: 'Diet',
            activity: 'Activity',
            stress: 'Stress',
            substance: 'Substance Use',
            stool: 'Stool',
            urine: 'Urine',
            menstruation: 'Menstruation',
            
            improvementReview: 'Patient Improvement Review',
            symptom: 'Symptom',
            reviewDate: 'Date',
            doctorName: 'Doctor Name',
            review: 'Review',
            status: 'Status',
            recoveryPercentage: 'Recovery %',
        }
    },
    aiInsights: {
        title: 'AI Health Analysis Engine',
        description: 'Click the button below to generate AI-powered health insights based on the complete patient report. Ensure all sections have been filled out for the most accurate analysis.',
        buttonText: 'Generate Insights from Full Report',
        buttonLoading: 'Analyzing Full Report...',
        errorTitle: 'Error Generating Insights',
        errorCardTitle: 'Error',
        resultsTitle: 'AI-Generated Insights',
        disclaimer: 'Disclaimer: The analysis below is generated by an AI and is for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.',
        summary: 'Diagnostic Summary',
        conditions: 'Potential Conditions & Problem Areas',
        recommendations: 'Lifestyle & Wellness Recommendations',
        nextSteps: 'Suggested Next Steps & Consultations',
    },
    patientImprovementReview: {
        title: 'Patient Improvement Review',
        description: 'Track symptoms and recovery progress over time.',
        addSymptomButton: 'Add Symptom Review',
        symptomPlaceholder: 'Describe the symptom or problem',
        dateLabel: 'Review Date',
        doctorNameLabel: 'Doctor\'s Name',
        doctorNamePlaceholder: 'e.g., Dr. Smith',
        reviewLabel: 'Rating',
        statusLabel: 'Status',
        statusRelieved: 'Relieved',
        statusNotRelieved: 'Not Relieved',
        recoveryLabel: 'Recovery Percentage',
    },
    consultation: {
        title: 'Doctor Consultation',
        description: 'Book and manage your appointments with specialists.',
        tabs: {
            booking: 'Book Appointment',
            session: 'Start Consultation',
        },
        booking: {
            title: 'Book an Appointment',
            selectDoctor: 'Select a Doctor',
            noDoctorSelected: 'Please select a doctor',
            addCustomDoctor: 'Add Custom Doctor',
            patientNameLabel: 'Patient Name',
            problemLabel: 'Symptom / Problem',
            problemPlaceholder: 'Briefly describe the reason for consultation',
            reportLabel: 'Upload Previous Report (Optional)',
            uniqueIdLabel: 'Patient Unique ID',
            bookButton: 'Book Appointment',
            selectDoctorFirst: 'Please select a doctor to proceed with payment and booking.',
            addDoctorDialog: {
                title: 'Add a Custom Doctor',
                description: 'Enter the details of the doctor you want to add.',
                nameLabel: 'Doctor\'s Name',
                specializationLabel: 'Specialization',
                addButton: 'Add Doctor',
                cancelButton: 'Cancel',
            },
        },
        session: {
            title: 'Your Consultation Session',
            description: 'Connect with your doctor using one of the methods below.',
            chatTitle: 'Live Chat',
            chatDesc: 'Start a text-based chat.',
            callTitle: 'Voice Call',
            callDesc: 'Start a voice call.',
            videoTitle: 'Video Conference',
            videoDesc: 'Start a video call.',
            uploadTitle: 'Upload Video Message',
            uploadDesc: 'Send a pre-recorded video.',
            startButton: 'Start',
            uploadButton: 'Upload',
            videoConference: {
                title: 'Video Conference',
                connecting: 'Connecting to Dr. {name}...',
                cameraErrorTitle: 'Camera Access Required',
                cameraErrorDesc: 'Please allow camera access in your browser to use this feature.',
            },
        },
        paymentForm: {
          title: 'Complete Booking Payment',
          description: 'You are paying a consultation fee of ₹{amount}.',
          card: {
              tabTitle: 'Credit/Debit Card',
              nameLabel: 'Name on Card',
              namePlaceholder: 'John Doe',
              numberLabel: 'Card Number',
              numberPlaceholder: '•••• •••• •••• ••••',
              expiryMonthLabel: 'Month',
              expiryYearLabel: 'Year',
              cvcLabel: 'CVC',
          },
          upi: {
              tabTitle: 'UPI',
              idLabel: 'UPI ID',
              idPlaceholder: 'yourname@upi',
              or: 'OR',
              gpay: 'GPay',
              phonepe: 'PhonePe',
              paytm: 'Paytm',
          },
          payButton: 'Pay ₹{amount} & Confirm Appointment',
      },
    }
  }
};
